# Generated by Django 5.2.6 on 2025-09-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='code',
        ),
    ]
