# Generated by Django 5.2.6 on 2025-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_courses_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
