# Generated by Django 5.2.6 on 2025-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_enrolled_course_term_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
