# Generated by Django 5.2.6 on 2025-10-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_code_alter_course_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
