# Generated by Django 5.2.6 on 2025-10-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
