# Generated by Django 5.2.6 on 2025-10-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_update_at_course_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('graduates', models.IntegerField()),
            ],
        ),
    ]
