# Generated by Django 5.2.6 on 2025-10-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_graduationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('prereq_1', models.CharField(blank=True, max_length=20, null=True)),
                ('prereq_2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
