# Generated by Django 5.2.6 on 2025-10-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
